kind: pipeline
type: docker
name: hx-h5-home

volumes:
  - name: cache
    host: 
      path: /tmp/cache

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules
      - ./yarn-cache
    
- name: build
  image: node:18
  pull: if-not-exists
  commands:
    - node -v
    - npm -v
    - yarn --version
    - yarn config set cache-folder /drone/src/yarn-cache
    - yarn install --pure-lockfile
    - yarn build

- name: rebuild-cache
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules
      - ./yarn-cache

- name: code style
  image: node:18
  pull: if-not-exists
  commands:
    - yarn lint:eslint
    - yarn lint:prettier
    - yarn lint:stylelint
    - yarn lint-staged

- name: deploy
  image: appleboy/drone-scp
  pull: always
  settings:
    host:
        from_secret: server_host
    username: root
    password:
        from_secret: ssh_password
    port: 22
    target: /var/www/hx-home
    source: 
      - dist
  when:
    branch: [master]

- name: ssh commands production
  image: appleboy/drone-ssh
  pull: always
  settings:
    host:
        from_secret: server_host
    username: root
    password:
        from_secret: ssh_password
    port: 22
    script:
      - echo hx-h5-home
  when:
    branch: [master]

trigger:
  branch:
    - master